version: '3.5'
services:
  zookeeper:
    image: debezium/zookeeper:1.6
    container_name: zookeeper
    expose:
      - 2181
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  mskafka:
    image: debezium/kafka:1.6
    container_name: mskafka
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_HOST_NAME=mskafka
    expose:
      - 9092
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    container_name: schema-registry
    environment:
      - HOSTNAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - "mskafka"

 
networks:
  default:
    external:
      name: kafkanet
